module.exports = [
  'wew',
  'lol',
  'lmao',
  'mty',
  'she\'s a very nice girl who will never be fully prepared for the first time once getting over his divorce ',
  'Stop pussy footing and use your kids to get a pic of them at that thicc organ boy cameron carpenter at the symphony tonight ',
  'Thats seriously fucked up for you to get back at japan for their crimes in the past 48 hours ',
  'why cant believe im missing the first boobs in the world that shit talk him for being an idiot',
  'Anyone who has literally been to rehab / detox more than one time probably shouldnt be fucking gay these days but we used to go out in the middle earth you faggot ',
  'ts and ps for today',
  'I was ok at any of those hobbies that are actually pretty fucking stupid shit ',
  'My favorite food is very cold to enjoy. pretty much the moment i lost faith in the medical industry',
  ' why"},{"name":"dandy","text":"if youre saying she is the type of person who has literally been the perfect troll opportunity ',
  'I would be very surprised if your brokerage firm is doing a craft mezcal line',
  'You have a solid place to escape the groypers\ in dallas box lads ',
  'I would take my life if you were the group slut looking for a ticket to the us to party for a year ',
  'Is it lindy to be a hot step sister because porn told me to stop doing it to feel fine ',
  'You guys should have a lot in common with anime chicks whose bath water bruce got a jar of the girls youve fucked would you fuck ',
  'Swig thanks for letting them sit too long and ruin them you fuck ',
  'How about you keep your eyes out of the girls pussy cakes for 1 hour ',
  'Will i have to deal with this shit all night?  Good morning cartoons are gonna me cum ',
  'theyd be paying that kind of money into an upswing and get absolutely pitted on the couch area ',
  'If yall wanna suck on that girl\'s like a poor mans blonde sophie turner ',
  'yep that s how your mom sits @barron trump ',
  'These dudes wearing ufc / tapout gear all over the chesticle are going to strengthen their dominant genes ',
  'The best leftists of social media really makes the rest of your efforts suck the blood meridian ',
  'Shes my favorite insta thots for me and mine tyvm 😌 ',
  'No idea why \"dems have decided to give up key lime pie " " name":"barron trump","text":"lol ',
  ' maybe ill take a break from the phone over the weekend my dude my dudes ',
  'I hate how artificial sweeteners leave that taste of the rampant alcoholism in the box office space jams ',
  'Chillin poolside with sum gaylord for a month',
  ' We were going skiing and took a shit on the wall with barbara bush"},{"name":"bryce","text":"i ',
  'the girls at the wedding obviously arent from here and i was inebriated with a hammer every time i heart a swig post ',
  ' youre saying she is the devil s jew trickery in dallas rn',
  '{ " name":"bryce","text":"so that mans very impressive bawks content keeps making sweg schekels'
];
