module.exports = [
  'Yes',
  'Hell yeah bro',
  'Fur sure',
  'It is decidedly so',
  'Without a doubt',
  'Yes, definitely',
  'You may rely on it',
  'As I see it, yes',
  'Most likely',
  'Outlook good',
  'It is certain',
  'Signs point to yes',
  'Nope',
  'No way, Jose',
  'Don\'t count on it',
  'Outlook not so good',
  'My reply is no',
  'probs not my dude'
  'Fuck no',
  'lol doubt it',
  'nah m8',
  'lol doubt it',
  'not a fucking chance',
  'Very doubtful',
  'Reply hazy try again',
  'Ask again later',
  'Better not tell you now',
  'Cannot predict now',
  'Concentrate and ask again',
  'Maybe. Maybe not. Maybe fuck yourself.',
  'you\'d like to know, wouldn\'t you faggot',
  'Better ask Big Brain Shane :-)',
  'Unsure. Better make a poll for it'
];
